# Generated by Django 6.1 on 2026-10-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(default='Naya Marina', max_length=120)),
                ('city', models.CharField(default='Cotonou', max_length=80)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('developer_name', models.CharField(blank=True, max_length=120)),
                ('demo_mode', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.PositiveSmallIntegerField(default=2)),
                ('price_per_night', models.PositiveIntegerField(help_text='Prix en FCFA')),
                ('image_url', models.URLField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
