# Generated by Django 6.1 on 2026-10-07 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='units_total',
            field=models.PositiveSmallIntegerField(default=1, help_text='Unités de cette catégorie dans la maquette'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=12, unique=True)),
                ('guest_name', models.CharField(max_length=160)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_phone', models.CharField(blank=True, max_length=40)),
                ('arrival', models.DateField()),
                ('departure', models.DateField()),
                ('guests', models.PositiveSmallIntegerField(default=1)),
                ('total_price', models.PositiveIntegerField(help_text='Montant indicatif en FCFA')),
                ('status', models.CharField(choices=[('pending', 'En attente de confirmation'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée')], default='pending', max_length=16)),
                ('payment_status', models.CharField(default='not_configured', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='core.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
