# Generated by Django 6.1 on 2026-10-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reservation_customer_customerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='fedapay_transaction_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(choices=[('not_configured', 'Paiement non configuré'), ('pending', 'Paiement en attente'), ('paid', 'Payée'), ('failed', 'Échouée ou annulée')], default='not_configured', max_length=16),
        ),
    ]
