# Generated by Django 6.1 on 2026-10-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_menuitem_alter_reservation_payment_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
