# Generated by Django 6.1 on 2026-10-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_hotelamenity_hotelinterior_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantorder',
            name='fedapay_transaction_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='payment_status',
            field=models.CharField(choices=[('not_configured', 'Paiement non configuré'), ('pending', 'Paiement en attente'), ('paid', 'Payée'), ('failed', 'Échouée ou annulée')], default='not_configured', max_length=16),
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='payment_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
