# Generated by Django 6.1 on 2026-10-07 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_restaurantorder_fedapay_transaction_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, unique=True)),
                ('customer_name', models.CharField(max_length=160)),
                ('customer_email', models.EmailField(max_length=254)),
                ('description', models.CharField(max_length=240)),
                ('amount', models.PositiveIntegerField(help_text='Montant facturé en FCFA')),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='core.reservation')),
                ('restaurant_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='core.restaurantorder')),
            ],
            options={
                'ordering': ['-issued_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('reservation__isnull', False), ('restaurant_order__isnull', True)), models.Q(('reservation__isnull', True), ('restaurant_order__isnull', False)), _connector='OR'), name='invoice_exactly_one_source')],
            },
        ),
    ]
