# Generated by Django 6.1 on 2026-10-07 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Ex. Haute saison, fêtes, week-end', max_length=100)),
                ('start_date', models.DateField(help_text='Premier jour où ce tarif s’applique')),
                ('end_date', models.DateField(help_text='Premier jour où ce tarif ne s’applique plus')),
                ('price_per_night', models.PositiveIntegerField(help_text='Prix par nuit en FCFA')),
                ('is_active', models.BooleanField(default=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_rates', to='core.room')),
            ],
            options={
                'ordering': ['start_date', 'room__name'],
                'indexes': [models.Index(fields=['room', 'is_active', 'start_date', 'end_date'], name='core_roomra_room_id_006595_idx')],
            },
        ),
    ]
