# Generated by Django 6.1 on 2026-10-07 23:57

import django.db.models.deletion
from django.db import migrations, models


def populate_room_units(apps, schema_editor):
    Room = apps.get_model("core", "Room")
    RoomUnit = apps.get_model("core", "RoomUnit")
    Reservation = apps.get_model("core", "Reservation")
    database = schema_editor.connection.alias

    for room in Room.objects.using(database).all().iterator():
        RoomUnit.objects.using(database).bulk_create([
            RoomUnit(room_id=room.pk, code=f"{number:03d}")
            for number in range(1, room.units_total + 1)
        ])

    active_reservations = Reservation.objects.using(database).filter(
        status__in=["pending", "confirmed"], room_unit__isnull=True
    ).order_by("arrival", "id")
    for reservation in active_reservations.iterator():
        occupied_ids = Reservation.objects.using(database).filter(
            room_id=reservation.room_id,
            status__in=["pending", "confirmed"],
            room_unit__isnull=False,
            arrival__lt=reservation.departure,
            departure__gt=reservation.arrival,
        ).values_list("room_unit_id", flat=True)
        unit = RoomUnit.objects.using(database).filter(
            room_id=reservation.room_id, is_active=True
        ).exclude(pk__in=occupied_ids).first()
        if unit:
            Reservation.objects.using(database).filter(pk=reservation.pk).update(room_unit_id=unit.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_roomrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='units_total',
            field=models.PositiveSmallIntegerField(default=1, help_text='Nombre d’unités physiques actives (mis à jour depuis la liste des chambres)'),
        ),
        migrations.CreateModel(
            name='RoomUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Identifiant interne : numéro de chambre ou code d’unité', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=160)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.room')),
            ],
            options={
                'ordering': ['room__name', 'code'],
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='room_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='core.roomunit', verbose_name='Chambre physique affectée'),
        ),
        migrations.AddConstraint(
            model_name='roomunit',
            constraint=models.UniqueConstraint(fields=('room', 'code'), name='unique_room_unit_code'),
        ),
        migrations.RunPython(populate_room_units, migrations.RunPython.noop),
    ]
