# Generated by Django 6.1 on 2026-10-08 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_room_units_total_roomunit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomunit',
            name='housekeeping_status',
            field=models.CharField(choices=[('clean', 'Propre et prête'), ('needs_cleaning', 'À nettoyer'), ('cleaning', 'Nettoyage en cours'), ('inspected', 'Contrôlée')], default='clean', max_length=20, verbose_name='État du ménage'),
        ),
        migrations.CreateModel(
            name='RoomBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('maintenance', 'Maintenance'), ('out_of_service', 'Hors service')], default='maintenance', max_length=20)),
                ('start_date', models.DateField(help_text='Premier jour bloqué')),
                ('end_date', models.DateField(help_text='Premier jour de retour à la disponibilité')),
                ('note', models.CharField(blank=True, max_length=240)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.roomunit')),
            ],
            options={
                'ordering': ['start_date', 'unit__code'],
            },
        ),
    ]
