# Generated by Django 6.1 on 2026-10-08 00:37

from django.db import migrations, models


def copy_existing_totals(apps, schema_editor):
    Invoice = apps.get_model("core", "Invoice")
    Invoice.objects.all().update(subtotal=models.F("amount"))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_roomunit_housekeeping_status_roomblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='subtotal',
            field=models.PositiveIntegerField(default=0, help_text='Montant hors taxe en FCFA'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_amount',
            field=models.PositiveIntegerField(default=0, help_text='Taxe incluse en FCFA'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Taux inclus au moment de l’émission', max_digits=5),
        ),
        migrations.RunPython(copy_existing_totals, migrations.RunPython.noop),
    ]
