# Generated by Django 6.1 on 2026-10-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_invoice_subtotal_invoice_tax_amount_invoice_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='email_verification_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='email_verification_code_hash',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
