# Generated by Django 6.1 on 2026-10-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_customerprofile_email_verification_code_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guarantee_status',
            field=models.CharField(choices=[('pending', 'Garantie à vérifier'), ('secured', 'Garantie vérifiée'), ('not_required', 'Garantie non exigée')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(choices=[('not_configured', 'Paiement non configuré'), ('pending', 'Paiement en attente'), ('paid', 'Payée'), ('failed', 'Échouée ou annulée'), ('refund_pending', 'Remboursement à traiter'), ('refunded', 'Remboursée')], default='not_configured', max_length=16),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de confirmation'), ('confirmed', 'Confirmée'), ('checked_in', 'Arrivée enregistrée'), ('checked_out', 'Départ enregistré'), ('cancelled', 'Annulée')], default='pending', max_length=16),
        ),
    ]
