# Generated by Django 6.1 on 2026-10-08 01:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_reservation_guarantee_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='fees_amount',
            field=models.PositiveIntegerField(default=0, help_text='Frais de séjour inclus dans le sous-total'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='fees_amount',
            field=models.PositiveIntegerField(default=0, help_text='Frais de séjour figés au moment de la demande, en FCFA'),
        ),
        migrations.AddField(
            model_name='roomrate',
            name='arrival_weekdays',
            field=models.JSONField(blank=True, default=list, help_text='Jours d’arrivée autorisés dans cette période ; vide=tous les jours'),
        ),
        migrations.AddField(
            model_name='roomrate',
            name='departure_weekdays',
            field=models.JSONField(blank=True, default=list, help_text='Jours de départ autorisés dans cette période ; vide=tous les jours'),
        ),
        migrations.AddField(
            model_name='roomrate',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='Réduction du tarif en pourcentage, de 0 à 90', validators=[django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='roomrate',
            name='maximum_nights',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='roomrate',
            name='minimum_nights',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='roomrate',
            name='weekdays',
            field=models.JSONField(blank=True, default=list, help_text='Jours applicables : 0=lundi à 6=dimanche ; vide=tous les jours'),
        ),
        migrations.CreateModel(
            name='RoomFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount_type', models.CharField(choices=[('fixed', 'Montant fixe en FCFA'), ('percent', 'Pourcentage du séjour')], default='fixed', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('per_night', models.BooleanField(default=False, help_text='Pour un montant fixe, multiplie par le nombre de nuits')),
                ('is_active', models.BooleanField(default=True)),
                ('room', models.ForeignKey(blank=True, help_text='Vide : frais appliqués à toutes les catégories', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='core.room')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
