# Generated by Django 6.1 on 2026-10-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_invoice_fees_amount_reservation_fees_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FedaPayWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=120, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(blank=True, max_length=80)),
                ('payload_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('received', 'Reçu'), ('processed', 'Traité'), ('ignored', 'Ignoré'), ('failed', 'À réessayer')], default='received', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=240)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AlterField(
            model_name='restaurantorder',
            name='payment_status',
            field=models.CharField(choices=[('not_configured', 'Paiement non configuré'), ('pending', 'Paiement en attente'), ('paid', 'Payée'), ('failed', 'Échouée ou annulée'), ('refund_pending', 'Remboursement à traiter'), ('refunded', 'Remboursée')], default='not_configured', max_length=16),
        ),
    ]
