# Generated by Django 6.1 on 2026-10-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_fedapaywebhookevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=240)),
                ('encrypted_content', models.TextField(blank=True, help_text='Contenu chiffré avec la clé d’outbox configurée côté serveur')),
                ('status', models.CharField(choices=[('queued', 'En attente de nouvel essai'), ('sending', 'En cours d’envoi'), ('sent', 'Envoyé'), ('failed', 'Échec définitif')], default='queued', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=120)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='core_emailo_status_a125e4_idx')],
            },
        ),
    ]
