# Generated by Django 6.1 on 2026-10-08 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_emailoutbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('capacity', models.PositiveSmallIntegerField(default=2)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('occupied', 'Occupée'), ('closed', 'Hors service')], default='available', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='track_stock',
            field=models.BooleanField(default=False, help_text='Décompte automatiquement le stock à la commande'),
        ),
        migrations.AddField(
            model_name='restaurantorderline',
            name='options',
            field=models.CharField(blank=True, help_text='Options choisies au moment de la commande', max_length=300),
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.restauranttable'),
        ),
        migrations.CreateModel(
            name='MenuOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('additional_price', models.PositiveIntegerField(default=0, help_text='Supplément en FCFA')),
                ('is_available', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.menuitem')),
            ],
            options={
                'ordering': ['item__name', 'name'],
                'unique_together': {('item', 'name')},
            },
        ),
    ]
