# Generated by Django 6.1 on 2026-10-08 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_businessauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(choices=[('not_configured', 'Paiement non configuré'), ('pending', 'Paiement en attente'), ('paid', 'Payée'), ('partially_paid', 'Partiellement payée'), ('failed', 'Échouée ou annulée'), ('refund_pending', 'Remboursement à traiter'), ('refunded', 'Remboursée')], default='not_configured', max_length=16),
        ),
        migrations.CreateModel(
            name='ReservationPaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='Montant reçu en FCFA')),
                ('method', models.CharField(choices=[('cash', 'Espèces'), ('transfer', 'Virement'), ('mobile_money', 'Mobile Money manuel'), ('card', 'Carte au terminal')], max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Référence bancaire ou ticket, si disponible', max_length=100)),
                ('received_by_label', models.CharField(blank=True, max_length=160)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_reservation_payments', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_payments', to='core.reservation')),
            ],
            options={
                'ordering': ['received_at', 'pk'],
            },
        ),
    ]
