# Generated by Django 6.1 on 2026-10-08 02:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_reservation_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('discount_type', models.CharField(choices=[('percent', 'Pourcentage'), ('fixed', 'Montant fixe en FCFA')], default='percent', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(help_text='Dernier jour d’utilisation inclus')),
                ('maximum_uses', models.PositiveIntegerField(blank=True, help_text='Laisser vide pour un nombre illimité', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-starts_on', 'code'],
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='discount_amount',
            field=models.PositiveIntegerField(default=0, help_text='Réduction figée lors de la réservation, en FCFA'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='promotion_code_used',
            field=models.CharField(blank=True, help_text='Code appliqué, conservé sur le dossier', max_length=32),
        ),
        migrations.AddField(
            model_name='reservation',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='core.promotioncode'),
        ),
    ]
