# Generated by Django 6.1 on 2026-10-08 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_promotioncode_reservation_discount_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='Montant effectivement remboursé en FCFA')),
                ('method', models.CharField(choices=[('fedapay_dashboard', 'FedaPay — tableau de bord'), ('transfer', 'Virement bancaire'), ('cash', 'Espèces'), ('mobile_money', 'Mobile Money manuel')], max_length=24)),
                ('reference', models.CharField(help_text='Référence du remboursement ou du justificatif', max_length=120)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('processed_by_label', models.CharField(blank=True, max_length=160)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_hotel_refunds', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='core.reservation')),
                ('restaurant_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='core.restaurantorder')),
            ],
            options={
                'ordering': ['-processed_at', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('reservation__isnull', False), ('restaurant_order__isnull', True)), models.Q(('reservation__isnull', True), ('restaurant_order__isnull', False)), _connector='OR'), name='refund_exactly_one_source')],
            },
        ),
    ]
