from django.contrib.auth import views as auth_views
from django.urls import path
from django.urls import reverse_lazy
from . import views

urlpatterns = [
    path("health/", views.healthcheck, name="healthcheck"),
    path("informations/", views.informations, name="informations"),
    path("newsletter/inscription/", views.inscription_newsletter, name="inscription_newsletter"),
    path("newsletter/confirmer/<str:token>/", views.confirmer_newsletter, name="newsletter_confirmer"),
    path("newsletter/desinscrire/<str:token>/", views.desinscrire_newsletter, name="newsletter_desinscrire"),
    path("installation/", views.installation, name="installation"),
    path("installation/etape/<int:etape>/", views.installation, name="installation_etape"),
    path("installation/terminee/", views.installation_terminee, name="installation_terminee"),
    path("reservation/", views.reserver, name="reserver"),
    path("recherche/", views.rechercher_chambres, name="recherche_chambres"),
    path("equipe/", views.tableau_equipe, name="tableau_equipe"),
    path("equipe/gestion/", views.tableau_gestion, name="tableau_gestion"),
    path("equipe/reception/", views.tableau_reception, name="tableau_reception"),
    path("equipe/restaurant/", views.tableau_restaurant, name="tableau_restaurant"),
    path("equipe/restaurant/cuisine/", views.commandes_cuisine, name="commandes_cuisine"),
    path("equipe/restaurant/cuisine/<str:reference>/", views.detail_commande_cuisine, name="detail_commande_cuisine"),
    path("equipe/restaurant/inventaire/", views.inventaire_restaurant, name="inventaire_restaurant"),
    path("equipe/personnel/", views.personnel, name="personnel"),
    path("equipe/planning/", views.planning_chambres, name="planning_chambres"),
    path("equipe/rapports/", views.rapport_gestion, name="rapport_gestion"),
    path("equipe/paiements/rapprochement/", views.rapprochement_paiements, name="rapprochement_paiements"),
    path("equipe/paiements/rapprochement/<str:source_type>/<str:reference>/", views.rapprocher_transaction_fedapay, name="rapprocher_transaction_fedapay"),
    path("equipe/reservation/<str:reference>/action/", views.action_reservation, name="action_reservation"),
    path("equipe/reservation/<str:reference>/", views.detail_reservation_equipe, name="detail_reservation_equipe"),
    path("equipe/restaurant/commande/<str:reference>/action/", views.action_commande_restaurant, name="action_commande_restaurant"),
    path("equipe/restaurant/stock/<int:item_id>/", views.action_stock_restaurant, name="action_stock_restaurant"),
    path("equipe/restaurant/stock/<int:item_id>/seuil/", views.action_seuil_stock_restaurant, name="action_seuil_stock_restaurant"),
    path("reservation/<str:reference>/", views.reservation_confirmee, name="reservation_confirmee"),
    path("paiement/<str:reference>/", views.initier_paiement, name="initier_paiement"),
    path("paiement/retour/<str:reference>/", views.retour_paiement, name="paiement_retour"),
    path("paiements/fedapay/webhook/", views.fedapay_webhook, name="fedapay_webhook"),
    path("facture/<str:number>/", views.consulter_facture, name="consulter_facture"),
    path("facture/<str:number>/pdf/", views.facture_pdf, name="facture_pdf"),
    path("restaurant/", views.restaurant, name="restaurant"),
    path("restaurant/commande/<str:reference>/", views.commande_confirmee, name="commande_confirmee"),
    path("restaurant/commande/<str:reference>/payer/", views.payer_commande, name="payer_commande"),
    path("restaurant/commande/<str:reference>/paiement-retour/", views.retour_paiement_commande, name="commande_paiement_retour"),
    path("compte/inscription/", views.inscription, name="inscription"),
    path("compte/connexion/", views.connexion, name="connexion"),
    path("compte/deconnexion/", views.deconnexion, name="deconnexion"),
    path("compte/verification/envoyee/", views.verification_envoyee, name="verification_envoyee"),
    path("compte/verification/renvoyer/", views.renvoyer_verification, name="renvoyer_verification"),
    path("compte/verification/<uidb64>/<token>/", views.verifier_email, name="verifier_email"),
    path("compte/mot-de-passe/oubli/", auth_views.PasswordResetView.as_view(template_name="core/password_reset.html", email_template_name="core/password_reset_email.html", subject_template_name="core/password_reset_subject.txt", success_url=reverse_lazy("password_reset_done")), name="password_reset"),
    path("compte/mot-de-passe/envoye/", auth_views.PasswordResetDoneView.as_view(template_name="core/password_reset_done.html"), name="password_reset_done"),
    path("compte/mot-de-passe/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(template_name="core/password_reset_confirm.html", success_url=reverse_lazy("password_reset_complete")), name="password_reset_confirm"),
    path("compte/mot-de-passe/termine/", auth_views.PasswordResetCompleteView.as_view(template_name="core/password_reset_complete.html"), name="password_reset_complete"),
    path("compte/", views.mon_compte, name="mon_compte"),
    path("compte/reservation/<str:reference>/avis/", views.deposer_avis, name="deposer_avis"),
    path("compte/reservation/<str:reference>/annuler/", views.annuler_reservation, name="annuler_reservation"),
    path("compte/reservation/<str:reference>/modifier/", views.modifier_reservation, name="modifier_reservation"),
    path("", views.accueil, name="accueil"),
]
